### ISSUE TITLE
Question about dBY

### ISSUE THREAD

**Issue by dipterix** [lihualei71/dbh#1]
Hi, @lihualei71 ,

Thanks for having developed such a great package. 

In your paper, `dBY` procedure is proposed under unspecified dependence,
> For arbitrary dependence, the dBY(α) procedure is safe, and uniformly more powerful than the BY(α) procedure.

Indeed it is more powerful than BY procedure. However, when I was trying out `dBY` on my simulation data (gaussian, with negative dependence and known covariance) using the code below, it seems the actual `FDP` was not controlled near **0.05**. Instead, the actual `FDP` was **0.16**.
```r
res <- dBH_mvgauss(zvals = zvals, Sigma = Sigma, side = "two", alpha = 0.05,
                   gamma = NULL, niter = 1, avals_type = "BH")
```

Could be an implementation bug?

**Comment by lihualei71** [comment]
Hi @dipterix,

Thanks for posting the question! Could you let me know how you generated the `zvals` and `Sigma` and how many independent samples you used to calculate the average FDP?

**Comment by dipterix** [comment]
Ah, it's my bad. I had some random seed that caused large FDP. I'm sorry I should've checked my code more carefully. 
I'll close this issue.

P.S.: Is there any plan for `dbh` to go on CRAN?
